//
// Created by 27464 on 2024/3/14.
//

#ifndef BASIC_TXT_PRODUCER_CUSTOMER_PATTERN_H
#define BASIC_TXT_PRODUCER_CUSTOMER_PATTERN_H


class Producer_Customer_Pattern {

};


#endif //BASIC_TXT_PRODUCER_CUSTOMER_PATTERN_H
